@host=https://dummyjson.com

###
# @name LoginUser
POST {{host}}/auth/login
Accept: application/json
Content-Type: application/json

{
    "username": "emilys",
	"password": "emilyspass",
    "expiresInMins": 30
}

###
# @name GetUser
@YOUR_ACCESS_TOKEN={{LoginUser.response.body.accessToken}}
GET {{host}}/auth/me
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{YOUR_ACCESS_TOKEN}}

###
# @name RefreshAuthSession
@YOUR_REFRESH_TOKEN={{LoginUser.response.body.refreshToken}}
POST {{host}}/auth/refresh
Accept: application/json
Content-Type: application/json

{
    "refreshToken": "{{YOUR_REFRESH_TOKEN}}",
    "expiresInMins": 30
}
